theme = "rose_pine_transparent"

[editor]
line-number = "relative"
true-color = true

[editor.cursor-shape]
insert = "bar"

[editor.statusline]
left = ["mode", "separator","spacer","version-control", "file-base-name"]
right = ["diagnostics", "spinner", "file-encoding", "file-type", "position-percentage", "position"]
separator = ""
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-inlay-hints = true

[keys.normal]
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
A-a = ["yank", "move_visual_line_down", "replace_with_yanked", "increment"]

[keys.normal.space]
w = ":write"
c = ":buffer-close"
q = ":quit"
